---
title: "Congrats!"
output: github_document
---

**Congratulations!** You've made it to the end of this mini course in R. Below are some additional resources to help you continue on your journey to mastering R!

* [YouTube Course: Comp Bio with R](https://www.youtube.com/playlist?list=PLA54E692040796EA5) 
* [Online Textbook: Advanced R by Hadley Wickham](https://adv-r.hadley.nz/) 
* [Analysis Factor R Tutorial Collection](https://www.theanalysisfactor.com/r/)
* [Blog: Long to Wide Formats in R](http://reasoniamhere.com/2013/09/26/switching-between-long-and-wide-formats-in-r/)
* [Series of Manuals by UC Riverside](http://manuals.bioinformatics.ucr.edu/)
* [Computational Genomics Course Materials](https://eacooper400.github.io/compGen8900.html)
* [Hitchhiker's Guide to Data Science, Machine Learning, R, Python](https://www.hadoop360.datasciencecentral.com/blog/hitchhiker-s-guide-to-data-science-machine-learning-r-python)
* [An Intro to ggplot2](https://seananderson.ca/ggplot2-fish554/)
* [Free Online Book: Fundamentals of Data Visualization by Claus O. Wilke](https://serialmentor.com/dataviz/)

## Need more data???
Try some of these downloadable practice datasets!

* [An International Journal on the Teaching and Learning of Statistics](http://jse.amstat.org/jse_data_archive.htm)
* [Kaggle](https://www.kaggle.com/)
* [PhysioNet: The Research Resource for Complex Physiologic Signals](https://physionet.org/)